//This file is automatically generated by CMAKE. DO NOT MODIFY.
using System;
using System.Collections.Generic;

namespace Emgu.CV
{
   public partial class CvInvoke
   {
      /// <summary>
      /// The file name of the cvextern library
      /// </summary>
#if UNITY_EDITOR_OSX
      public const string ExternLibrary = "Assets/Emgu.CV/Plugins/emgucv.bundle/Contents/MacOS/libcvextern.dylib";
#elif UNITY_STANDALONE_OSX
      public const string ExternLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libcvextern.dylib";
#elif (__IOS__ || UNITY_IPHONE) && (!UNITY_EDITOR_WIN)
      public const string ExternLibrary = "__Internal";
#else
      public const string ExternLibrary = "cvextern";
#endif
	  
      /// <summary>
      /// The file name of the cvextern library
      /// </summary>
      public const string ExternCudaLibrary = ExternLibrary;

      /// <summary>
      /// The file name of the opencv_ffmpeg library
      /// </summary>
      public const string OpencvFFMpegLibrary = "opencv_videoio_ffmpeg440_64";

       
      /// <summary>
      /// The file name of the core library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCoreLibrary = "opencv_core440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCoreLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_core.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCoreLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_core.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCoreLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCoreLibrary = "opencv_core";
      #else
      public const string OpencvCoreLibrary = "opencv_core440";
      #endif
 
      /// <summary>
      /// The file name of the imgproc library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvImgprocLibrary = "opencv_imgproc440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvImgprocLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_imgproc.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvImgprocLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_imgproc.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvImgprocLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvImgprocLibrary = "opencv_imgproc";
      #else
      public const string OpencvImgprocLibrary = "opencv_imgproc440";
      #endif
 
      /// <summary>
      /// The file name of the video library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvVideoLibrary = "opencv_video440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvVideoLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_video.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvVideoLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_video.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvVideoLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvVideoLibrary = "opencv_video";
      #else
      public const string OpencvVideoLibrary = "opencv_video440";
      #endif
 
      /// <summary>
      /// The file name of the flann library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvFlannLibrary = "opencv_flann440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvFlannLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_flann.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvFlannLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_flann.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvFlannLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvFlannLibrary = "opencv_flann";
      #else
      public const string OpencvFlannLibrary = "opencv_flann440";
      #endif
 
      /// <summary>
      /// The file name of the ml library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvMlLibrary = "opencv_ml440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvMlLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_ml.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvMlLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_ml.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvMlLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvMlLibrary = "opencv_ml";
      #else
      public const string OpencvMlLibrary = "opencv_ml440";
      #endif
 
      /// <summary>
      /// The file name of the imgcodecs library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvImgcodecsLibrary = "opencv_imgcodecs440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvImgcodecsLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_imgcodecs.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvImgcodecsLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_imgcodecs.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvImgcodecsLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvImgcodecsLibrary = "opencv_imgcodecs";
      #else
      public const string OpencvImgcodecsLibrary = "opencv_imgcodecs440";
      #endif
 
      /// <summary>
      /// The file name of the videoio library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvVideoioLibrary = "opencv_videoio440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvVideoioLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_videoio.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvVideoioLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_videoio.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvVideoioLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvVideoioLibrary = "opencv_videoio";
      #else
      public const string OpencvVideoioLibrary = "opencv_videoio440";
      #endif
 
      /// <summary>
      /// The file name of the highgui library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvHighguiLibrary = "opencv_highgui440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvHighguiLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_highgui.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvHighguiLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_highgui.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvHighguiLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvHighguiLibrary = "opencv_highgui";
      #else
      public const string OpencvHighguiLibrary = "opencv_highgui440";
      #endif
 
      /// <summary>
      /// The file name of the objdetect library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvObjdetectLibrary = "opencv_objdetect440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvObjdetectLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_objdetect.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvObjdetectLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_objdetect.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvObjdetectLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvObjdetectLibrary = "opencv_objdetect";
      #else
      public const string OpencvObjdetectLibrary = "opencv_objdetect440";
      #endif
 
      /// <summary>
      /// The file name of the features2d library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvFeatures2dLibrary = "opencv_features2d440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvFeatures2dLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_features2d.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvFeatures2dLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_features2d.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvFeatures2dLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvFeatures2dLibrary = "opencv_features2d";
      #else
      public const string OpencvFeatures2dLibrary = "opencv_features2d440";
      #endif
 
      /// <summary>
      /// The file name of the calib3d library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCalib3dLibrary = "opencv_calib3d440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCalib3dLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_calib3d.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCalib3dLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_calib3d.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCalib3dLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCalib3dLibrary = "opencv_calib3d";
      #else
      public const string OpencvCalib3dLibrary = "opencv_calib3d440";
      #endif
 
      /// <summary>
      /// The file name of the cudaarithm library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudaarithmLibrary = "opencv_cudaarithm440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudaarithmLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaarithm.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudaarithmLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaarithm.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudaarithmLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudaarithmLibrary = "opencv_cudaarithm";
      #else
      public const string OpencvCudaarithmLibrary = "opencv_cudaarithm440";
      #endif
 
      /// <summary>
      /// The file name of the cudawarping library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudawarpingLibrary = "opencv_cudawarping440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudawarpingLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudawarping.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudawarpingLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudawarping.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudawarpingLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudawarpingLibrary = "opencv_cudawarping";
      #else
      public const string OpencvCudawarpingLibrary = "opencv_cudawarping440";
      #endif
 
      /// <summary>
      /// The file name of the cudafilters library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudafiltersLibrary = "opencv_cudafilters440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudafiltersLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudafilters.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudafiltersLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudafilters.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudafiltersLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudafiltersLibrary = "opencv_cudafilters";
      #else
      public const string OpencvCudafiltersLibrary = "opencv_cudafilters440";
      #endif
 
      /// <summary>
      /// The file name of the cudaimgproc library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudaimgprocLibrary = "opencv_cudaimgproc440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudaimgprocLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaimgproc.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudaimgprocLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaimgproc.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudaimgprocLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudaimgprocLibrary = "opencv_cudaimgproc";
      #else
      public const string OpencvCudaimgprocLibrary = "opencv_cudaimgproc440";
      #endif
 
      /// <summary>
      /// The file name of the cudalegacy library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudalegacyLibrary = "opencv_cudalegacy440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudalegacyLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudalegacy.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudalegacyLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudalegacy.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudalegacyLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudalegacyLibrary = "opencv_cudalegacy";
      #else
      public const string OpencvCudalegacyLibrary = "opencv_cudalegacy440";
      #endif
 
      /// <summary>
      /// The file name of the cudaoptflow library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudaoptflowLibrary = "opencv_cudaoptflow440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudaoptflowLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaoptflow.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudaoptflowLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaoptflow.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudaoptflowLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudaoptflowLibrary = "opencv_cudaoptflow";
      #else
      public const string OpencvCudaoptflowLibrary = "opencv_cudaoptflow440";
      #endif
 
      /// <summary>
      /// The file name of the cudastereo library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudastereoLibrary = "opencv_cudastereo440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudastereoLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudastereo.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudastereoLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudastereo.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudastereoLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudastereoLibrary = "opencv_cudastereo";
      #else
      public const string OpencvCudastereoLibrary = "opencv_cudastereo440";
      #endif
 
      /// <summary>
      /// The file name of the cudabgsegm library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudabgsegmLibrary = "opencv_cudabgsegm440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudabgsegmLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudabgsegm.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudabgsegmLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudabgsegm.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudabgsegmLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudabgsegmLibrary = "opencv_cudabgsegm";
      #else
      public const string OpencvCudabgsegmLibrary = "opencv_cudabgsegm440";
      #endif
 
      /// <summary>
      /// The file name of the cudafeatures2d library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudafeatures2dLibrary = "opencv_cudafeatures2d440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudafeatures2dLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudafeatures2d.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudafeatures2dLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudafeatures2d.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudafeatures2dLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudafeatures2dLibrary = "opencv_cudafeatures2d";
      #else
      public const string OpencvCudafeatures2dLibrary = "opencv_cudafeatures2d440";
      #endif
 
      /// <summary>
      /// The file name of the cudacodec library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudacodecLibrary = "opencv_cudacodec440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudacodecLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudacodec.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudacodecLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudacodec.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudacodecLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudacodecLibrary = "opencv_cudacodec";
      #else
      public const string OpencvCudacodecLibrary = "opencv_cudacodec440";
      #endif
 
      /// <summary>
      /// The file name of the cudaobjdetect library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudaobjdetectLibrary = "opencv_cudaobjdetect440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudaobjdetectLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaobjdetect.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudaobjdetectLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudaobjdetect.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudaobjdetectLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudaobjdetectLibrary = "opencv_cudaobjdetect";
      #else
      public const string OpencvCudaobjdetectLibrary = "opencv_cudaobjdetect440";
      #endif
 
      /// <summary>
      /// The file name of the photo library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvPhotoLibrary = "opencv_photo440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvPhotoLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_photo.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvPhotoLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_photo.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvPhotoLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvPhotoLibrary = "opencv_photo";
      #else
      public const string OpencvPhotoLibrary = "opencv_photo440";
      #endif
 
      /// <summary>
      /// The file name of the superres library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvSuperresLibrary = "opencv_superres440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvSuperresLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_superres.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvSuperresLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_superres.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvSuperresLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvSuperresLibrary = "opencv_superres";
      #else
      public const string OpencvSuperresLibrary = "opencv_superres440";
      #endif
 
      /// <summary>
      /// The file name of the videostab library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvVideostabLibrary = "opencv_videostab440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvVideostabLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_videostab.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvVideostabLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_videostab.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvVideostabLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvVideostabLibrary = "opencv_videostab";
      #else
      public const string OpencvVideostabLibrary = "opencv_videostab440";
      #endif
 
      /// <summary>
      /// The file name of the shape library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvShapeLibrary = "opencv_shape440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvShapeLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_shape.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvShapeLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_shape.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvShapeLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvShapeLibrary = "opencv_shape";
      #else
      public const string OpencvShapeLibrary = "opencv_shape440";
      #endif
 
      /// <summary>
      /// The file name of the cudev library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvCudevLibrary = "opencv_cudev440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvCudevLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudev.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvCudevLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_cudev.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvCudevLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvCudevLibrary = "opencv_cudev";
      #else
      public const string OpencvCudevLibrary = "opencv_cudev440";
      #endif
 
      /// <summary>
      /// The file name of the face library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvFaceLibrary = "opencv_face440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvFaceLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_face.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvFaceLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_face.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvFaceLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvFaceLibrary = "opencv_face";
      #else
      public const string OpencvFaceLibrary = "opencv_face440";
      #endif
 
      /// <summary>
      /// The file name of the ximgproc library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvXimgprocLibrary = "opencv_ximgproc440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvXimgprocLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_ximgproc.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvXimgprocLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_ximgproc.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvXimgprocLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvXimgprocLibrary = "opencv_ximgproc";
      #else
      public const string OpencvXimgprocLibrary = "opencv_ximgproc440";
      #endif
 
      /// <summary>
      /// The file name of the xobjdetect library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvXobjdetectLibrary = "opencv_xobjdetect440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvXobjdetectLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_xobjdetect.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvXobjdetectLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_xobjdetect.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvXobjdetectLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvXobjdetectLibrary = "opencv_xobjdetect";
      #else
      public const string OpencvXobjdetectLibrary = "opencv_xobjdetect440";
      #endif
 
      /// <summary>
      /// The file name of the xfeatures2d library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvXfeatures2dLibrary = "opencv_xfeatures2d440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvXfeatures2dLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_xfeatures2d.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvXfeatures2dLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_xfeatures2d.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvXfeatures2dLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvXfeatures2dLibrary = "opencv_xfeatures2d";
      #else
      public const string OpencvXfeatures2dLibrary = "opencv_xfeatures2d440";
      #endif
 
      /// <summary>
      /// The file name of the xphoto library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvXphotoLibrary = "opencv_xphoto440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvXphotoLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_xphoto.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvXphotoLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_xphoto.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvXphotoLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvXphotoLibrary = "opencv_xphoto";
      #else
      public const string OpencvXphotoLibrary = "opencv_xphoto440";
      #endif
 
      /// <summary>
      /// The file name of the bgsegm library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvBgsegmLibrary = "opencv_bgsegm440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvBgsegmLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_bgsegm.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvBgsegmLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_bgsegm.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvBgsegmLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvBgsegmLibrary = "opencv_bgsegm";
      #else
      public const string OpencvBgsegmLibrary = "opencv_bgsegm440";
      #endif
 
      /// <summary>
      /// The file name of the optflow library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvOptflowLibrary = "opencv_optflow440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvOptflowLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_optflow.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvOptflowLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_optflow.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvOptflowLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvOptflowLibrary = "opencv_optflow";
      #else
      public const string OpencvOptflowLibrary = "opencv_optflow440";
      #endif
 
      /// <summary>
      /// The file name of the stitching library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvStitchingLibrary = "opencv_stitching440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvStitchingLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_stitching.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvStitchingLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_stitching.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvStitchingLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvStitchingLibrary = "opencv_stitching";
      #else
      public const string OpencvStitchingLibrary = "opencv_stitching440";
      #endif
 
      /// <summary>
      /// The file name of the plot library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvPlotLibrary = "opencv_plot440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvPlotLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_plot.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvPlotLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_plot.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvPlotLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvPlotLibrary = "opencv_plot";
      #else
      public const string OpencvPlotLibrary = "opencv_plot440";
      #endif
 
      /// <summary>
      /// The file name of the dnn library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvDnnLibrary = "opencv_dnn440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvDnnLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_dnn.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvDnnLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_dnn.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvDnnLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvDnnLibrary = "opencv_dnn";
      #else
      public const string OpencvDnnLibrary = "opencv_dnn440";
      #endif
 
      /// <summary>
      /// The file name of the dnn_objdetect library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvDnn_objdetectLibrary = "opencv_dnn_objdetect440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvDnn_objdetectLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_dnn_objdetect.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvDnn_objdetectLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_dnn_objdetect.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvDnn_objdetectLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvDnn_objdetectLibrary = "opencv_dnn_objdetect";
      #else
      public const string OpencvDnn_objdetectLibrary = "opencv_dnn_objdetect440";
      #endif
 
      /// <summary>
      /// The file name of the dnn_superres library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvDnn_superresLibrary = "opencv_dnn_superres440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvDnn_superresLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_dnn_superres.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvDnn_superresLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_dnn_superres.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvDnn_superresLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvDnn_superresLibrary = "opencv_dnn_superres";
      #else
      public const string OpencvDnn_superresLibrary = "opencv_dnn_superres440";
      #endif
 
      /// <summary>
      /// The file name of the aruco library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvArucoLibrary = "opencv_aruco440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvArucoLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_aruco.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvArucoLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_aruco.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvArucoLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvArucoLibrary = "opencv_aruco";
      #else
      public const string OpencvArucoLibrary = "opencv_aruco440";
      #endif
 
      /// <summary>
      /// The file name of the fuzzy library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvFuzzyLibrary = "opencv_fuzzy440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvFuzzyLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_fuzzy.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvFuzzyLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_fuzzy.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvFuzzyLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvFuzzyLibrary = "opencv_fuzzy";
      #else
      public const string OpencvFuzzyLibrary = "opencv_fuzzy440";
      #endif
 
      /// <summary>
      /// The file name of the viz library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvVizLibrary = "opencv_viz440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvVizLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_viz.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvVizLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_viz.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvVizLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvVizLibrary = "opencv_viz";
      #else
      public const string OpencvVizLibrary = "opencv_viz440";
      #endif
 
      /// <summary>
      /// The file name of the bioinspired library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvBioinspiredLibrary = "opencv_bioinspired440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvBioinspiredLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_bioinspired.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvBioinspiredLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_bioinspired.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvBioinspiredLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvBioinspiredLibrary = "opencv_bioinspired";
      #else
      public const string OpencvBioinspiredLibrary = "opencv_bioinspired440";
      #endif
 
      /// <summary>
      /// The file name of the text library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvTextLibrary = "opencv_text440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvTextLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_text.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvTextLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_text.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvTextLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvTextLibrary = "opencv_text";
      #else
      public const string OpencvTextLibrary = "opencv_text440";
      #endif
 
      /// <summary>
      /// The file name of the tracking library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvTrackingLibrary = "opencv_tracking440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvTrackingLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_tracking.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvTrackingLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_tracking.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvTrackingLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvTrackingLibrary = "opencv_tracking";
      #else
      public const string OpencvTrackingLibrary = "opencv_tracking440";
      #endif
 
      /// <summary>
      /// The file name of the dpm library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvDpmLibrary = "opencv_dpm440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvDpmLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_dpm.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvDpmLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_dpm.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvDpmLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvDpmLibrary = "opencv_dpm";
      #else
      public const string OpencvDpmLibrary = "opencv_dpm440";
      #endif
 
      /// <summary>
      /// The file name of the saliency library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvSaliencyLibrary = "opencv_saliency440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvSaliencyLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_saliency.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvSaliencyLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_saliency.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvSaliencyLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvSaliencyLibrary = "opencv_saliency";
      #else
      public const string OpencvSaliencyLibrary = "opencv_saliency440";
      #endif
 
      /// <summary>
      /// The file name of the img_hash library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvImg_hashLibrary = "opencv_img_hash440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvImg_hashLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_img_hash.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvImg_hashLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_img_hash.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvImg_hashLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvImg_hashLibrary = "opencv_img_hash";
      #else
      public const string OpencvImg_hashLibrary = "opencv_img_hash440";
      #endif
 
      /// <summary>
      /// The file name of the phase_unwrapping library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvPhase_unwrappingLibrary = "opencv_phase_unwrapping440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvPhase_unwrappingLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_phase_unwrapping.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvPhase_unwrappingLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_phase_unwrapping.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvPhase_unwrappingLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvPhase_unwrappingLibrary = "opencv_phase_unwrapping";
      #else
      public const string OpencvPhase_unwrappingLibrary = "opencv_phase_unwrapping440";
      #endif
 
      /// <summary>
      /// The file name of the freetype library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvFreetypeLibrary = "opencv_freetype440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvFreetypeLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_freetype.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvFreetypeLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_freetype.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvFreetypeLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvFreetypeLibrary = "opencv_freetype";
      #else
      public const string OpencvFreetypeLibrary = "opencv_freetype440";
      #endif
 
      /// <summary>
      /// The file name of the hfs library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvHfsLibrary = "opencv_hfs440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvHfsLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_hfs.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvHfsLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_hfs.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvHfsLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvHfsLibrary = "opencv_hfs";
      #else
      public const string OpencvHfsLibrary = "opencv_hfs440";
      #endif
 
      /// <summary>
      /// The file name of the quality library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvQualityLibrary = "opencv_quality440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvQualityLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_quality.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvQualityLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_quality.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvQualityLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvQualityLibrary = "opencv_quality";
      #else
      public const string OpencvQualityLibrary = "opencv_quality440";
      #endif
 
      /// <summary>
      /// The file name of the stereo library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvStereoLibrary = "opencv_stereo440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvStereoLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_stereo.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvStereoLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_stereo.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvStereoLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvStereoLibrary = "opencv_stereo";
      #else
      public const string OpencvStereoLibrary = "opencv_stereo440";
      #endif
 
      /// <summary>
      /// The file name of the surface_matching library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvSurface_matchingLibrary = "opencv_surface_matching440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvSurface_matchingLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_surface_matching.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvSurface_matchingLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_surface_matching.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvSurface_matchingLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvSurface_matchingLibrary = "opencv_surface_matching";
      #else
      public const string OpencvSurface_matchingLibrary = "opencv_surface_matching440";
      #endif
 
      /// <summary>
      /// The file name of the alphamat library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvAlphamatLibrary = "opencv_alphamat440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvAlphamatLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_alphamat.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvAlphamatLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_alphamat.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvAlphamatLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvAlphamatLibrary = "opencv_alphamat";
      #else
      public const string OpencvAlphamatLibrary = "opencv_alphamat440";
      #endif
 
      /// <summary>
      /// The file name of the intensity_transform library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvIntensity_transformLibrary = "opencv_intensity_transform440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvIntensity_transformLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_intensity_transform.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvIntensity_transformLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_intensity_transform.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvIntensity_transformLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvIntensity_transformLibrary = "opencv_intensity_transform";
      #else
      public const string OpencvIntensity_transformLibrary = "opencv_intensity_transform440";
      #endif
 
      /// <summary>
      /// The file name of the rapid library
      /// </summary>
      #if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
      public const string OpencvRapidLibrary = "opencv_rapid440";
      #elif UNITY_EDITOR_OSX
      public const string OpencvRapidLibrary = "Assets/Plugins/emgucv.bundle/Contents/MacOS/libopencv_rapid.4.4.0.dylib";   
      #elif UNITY_STANDALONE_OSX
      public const string OpencvRapidLibrary = "@executable_path/../Plugins/emgucv.bundle/Contents/MacOS/libopencv_rapid.4.4.0.dylib";   
      #elif __IOS__ || UNITY_IPHONE
      public const string OpencvRapidLibrary = "__Internal";
      #elif __ANDROID__ || UNITY_ANDROID
      public const string OpencvRapidLibrary = "opencv_rapid";
      #else
      public const string OpencvRapidLibrary = "opencv_rapid440";
      #endif

	  
      /// <summary>
      /// The List of the opencv modules
      /// </summary>
	  public static List<String> OpenCVModuleList = new List<String>
	  {
#if !(__ANDROID__ || __IOS__ || UNITY_IPHONE || UNITY_ANDROID || NETFX_CORE)
        OpencvFFMpegLibrary,
#endif        
        
      OpencvCoreLibrary,
      OpencvImgprocLibrary,
      OpencvVideoLibrary,
      OpencvFlannLibrary,
      OpencvMlLibrary,
      OpencvImgcodecsLibrary,
      OpencvVideoioLibrary,
      OpencvHighguiLibrary,
      OpencvObjdetectLibrary,
      OpencvFeatures2dLibrary,
      OpencvCalib3dLibrary,
      OpencvCudaarithmLibrary,
      OpencvCudawarpingLibrary,
      OpencvCudafiltersLibrary,
      OpencvCudaimgprocLibrary,
      OpencvCudalegacyLibrary,
      OpencvCudaoptflowLibrary,
      OpencvCudastereoLibrary,
      OpencvCudabgsegmLibrary,
      OpencvCudafeatures2dLibrary,
      OpencvCudacodecLibrary,
      OpencvCudaobjdetectLibrary,
      OpencvPhotoLibrary,
      OpencvSuperresLibrary,
      OpencvVideostabLibrary,
      OpencvShapeLibrary,
      OpencvCudevLibrary,
      OpencvFaceLibrary,
      OpencvXimgprocLibrary,
      OpencvXobjdetectLibrary,
      OpencvXfeatures2dLibrary,
      OpencvXphotoLibrary,
      OpencvBgsegmLibrary,
      OpencvOptflowLibrary,
      OpencvStitchingLibrary,
      OpencvPlotLibrary,
      OpencvDnnLibrary,
      OpencvDnn_objdetectLibrary,
      OpencvDnn_superresLibrary,
      OpencvArucoLibrary,
      OpencvFuzzyLibrary,
      OpencvVizLibrary,
      OpencvBioinspiredLibrary,
      OpencvTextLibrary,
      OpencvTrackingLibrary,
      OpencvDpmLibrary,
      OpencvSaliencyLibrary,
      OpencvImg_hashLibrary,
      OpencvPhase_unwrappingLibrary,
      OpencvFreetypeLibrary,
      OpencvHfsLibrary,
      OpencvQualityLibrary,
      OpencvStereoLibrary,
      OpencvSurface_matchingLibrary,
      OpencvAlphamatLibrary,
      OpencvIntensity_transformLibrary,
      OpencvRapidLibrary,
        ExternLibrary
      };

	  
   }
}
